### ISSUE TITLE
Packaging choose to debian

### ISSUE THREAD

**Issue by franklintimoteo** [theryangeary/choose#54]
Hello! I'm trying package to debian, but have some errors. Do you know what it could be?

 test tests::test_process_escapes::test_unicode_crab_emoji ... FAILED test tests::test_process_escapes::test_unicode_u7fff ... FAILED failures: ---- tests::test_process_escapes::test_unicode_crab_emoji stdout ---- thread 'tests::test_process_escapes::test_unicode_crab_emoji' panicked at 'not implemented: `escape_ unicode` is not yet implemented', src/lib.rs:50:5 stack backtrace: 0: rust_begin_unwind at /usr/src/rustc-1.59.0/library/std/src/panicking.rs:498:5 1: core::panicking::panic_fmt at /usr/src/rustc-1.59.0/library/core/src/panicking.rs:116:14 2: backslash::escape_unicode at /usr/share/cargo/registry/backslash-0.2.0/src/lib.rs:50:5 3: backslash::tests::test_process_escapes::test_unicode_crab_emoji at /usr/share/cargo/registry/backslash-0.2.0/src/lib.rs:219:17 4: backslash::tests::test_process_escapes::test_unicode_crab_emoji::{{closure}} at /usr/share/cargo/registry/backslash-0.2.0/src/lib.rs:216:9 5: core::ops::function::FnOnce::call_once at /usr/src/rustc-1.59.0/library/core/src/ops/function.rs:227:5 6: core::ops::function::FnOnce::call_once at /usr/src/rustc-1.59.0/library/core/src/ops/function.rs:227:5 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace. ---- tests::test_process_escapes::test_unicode_u7fff stdout ---- thread 'tests::test_process_escapes::test_unicode_u7fff' panicked at 'not implemented: `escape_unico de` is not yet implemented', src/lib.rs:50:5 stack backtrace:

**Comment by theryangeary** [comment]
Hi @franklintimoteo,
Sorry for the delayed response. Can you run:
```
# make sure code is up to date
git fetch
git checkout origin/develop
# make sure rust is up to date
rustup update
```

This way we know we are on the same versions of code and rust.

Then can you share the output of:
```
rustup show
cargo test
test/e2e_test.sh
```

Please show the commands AND their output, and use triple backticks around the output to make it more readable.

Can you also share which debian version you are on?

**Comment by theryangeary** [comment]
Is there any chance you're building the tests for `backslash`: https://github.com/theryangeary/backslash ? The failing tests look like they are coming from there.

**Comment by shalak** [comment]
@franklintimoteo Did you have any luck with building the deb version?

**Comment by theryangeary** [comment]
going to close this out as it is quite old. prefer to install with `cargo` or `brew`. contributions for .deb packaging are welcome.
